# Site settings
url: https://gibbstuff.github.io
name: 'Gibbs Tuff'
title: 'Selling Gibbs Brand Lubricant'
description: Selling Gibbs Brand Lubricant

# Gems
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock

# Build Settings
sass:
  sass_dir: _sass
  style: compressed

# Configuration
ga_track_id: UA-12642425-1
twitter_id: iamchristinabot
instagram_id: iamchristinabot
pinterest_id: iamchristinabot
linkedin_id: christinadobi
email: iamchristinabot@gmail.com
form: "https://docs.google.com/forms/d/e/sample/formResponse"
